### ISSUE TITLE
Using MCP4725 with Timer2

### ISSUE THREAD

**Issue by circuitry2** [adafruit/Adafruit_MCP4725#11]
Hello, I am trying to output a sine wave using my MCP4725 with interrupts, as shown here:
http://interface.khm.de/index.php/lab/interfaces-advanced/arduino-dds-sinewave-generator/

As soon as I add a Timer 2 interrupt handler (ISR(TIMER2_OVF_vect)) I can no longer write to MCP4725. Is this because MCP4725 utilizes Wire.h, which uses Timer 2? Is there any way I can get around this limitation?

**Comment by ladyada** [comment]
No idea what it could be, we dont use any Timer in this library!
