### ISSUE TITLE
Dependency BusIO missing

### ISSUE THREAD

**Issue by samboy1111** [adafruit/Adafruit_MCP4725#17]
- Arduino board:  Arduino UNO (doesn't matter)

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.8.13 (doesn't matter)

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): 

1. install this library
2. create a minimal arduino code as below
```
#include <Adafruit_MCP4725.h>
void setup() {
  // put your setup code here, to run once:
}

void loop() {
  // put your main code here, to run repeatedly:
}
```

You will get

> fatal error: Adafruit_BusIO_Register.h: No such file or directory

- Proposed fix: Add [BusIO](https://github.com/adafruit/Adafruit_BusIO) to the list of dependencies of this library.

**Comment by ladyada** [comment]
it is listed as a dependancy, modern arduino IDE should add it for you already.
https://github.com/adafruit/Adafruit_MCP4725/blob/master/library.properties#L10
